name: Build the Todo App

on: workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       name: Checkout Code

     - name: Install Node
       uses: actions/setup-node@v3
       with:
          node-version: 12.2.0
          
     - name: Install Dependencies
       run: |
          npm install
     - name: Build Project
       run: npm run build
          
     - name: Upload artifact to enable deployment
       uses: actions/upload-artifact@v3
       with:
          name: poduction file
          path: ./build
      
  Deploy: 
  
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: poduction file
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.KEY }} #this is the key of the access token
          publish_dir: ./build    

    
        
       
  
